[tools]
node = "23"
python = "3.11.10"
go = "latest"
pnpm = "latest"
uv = "latest"
terraform = "latest"
task = "latest"
hadolint = "latest"
helm = "latest"
k9s = "latest"
shellcheck = "latest"
lefthook = "latest"
bun = "latest"
starship = "latest"
usage = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
